---
engines:
  eslint:
    enabled: true
    exclude_paths:
      - "eslint.config.mjs"
      - "eslint-config.ts"
      - "eslint-config.js"
      - "postcss.config.js"
      - "supabase/migrations/20240318000000_add_email_verified_to_profiles.sql"   
      - "README.md"
  jshint:
    enabled: false
exclude_paths:
  - "eslint.config.mjs"
  - "eslint-config.ts" 
  - "eslint-config.js"
  - "postcss.config.js"
  - "supabase/migrations/20240318000000_add_email_verified_to_profiles.sql"
  - "README.md"