---
engines:
  eslint:
    enabled: true
    exclude_paths:
      - "eslint.config.mjs"
      - "eslint-config.ts"
      - "eslint-config.js"
      - "postcss.config.js"
      - "supabase/migrations/20240318000000_add_email_verified_to_profiles.sql"   
      - "README.md"
      - "src/App.tsx"
      - "src/index.tsx"
      - "src/main.tsx"
      - "src/App.css"  


  jshint:
    enabled: false
  stylelint:
    enabled: false
exclude_paths:
  - "eslint.config.mjs"
  - "eslint-config.ts" 
  - "eslint-config.js"
  - "postcss.config.js"
  - "supabase/migrations/20240318000000_add_email_verified_to_profiles.sql"
  - "README.md"
  - "src/App.tsx"
  - "src/index.tsx"
  - "src/main.tsx"
  - "src/App.css"
  - "src/hooks/"