
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './custom-types';

const SUPABASE_URL = "https://kdnqdigveyozsnoambph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkbnFkaWd2ZXlvenNub2FtYnBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MzE5ODMsImV4cCI6MjA2MDMwNzk4M30.LPSxgM8T3oWEp2FTJ0PPPGmVI04BAPDhIjUYXarjeTY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  db: {
    schema: 'public',
  },
  global: {
    headers: {
      'x-app-name': 'safedrop',
    },
  },
});

// SQL statements for creating tables
export const createProfilesTableSql = `
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY,
  first_name TEXT,
  last_name TEXT,
  phone TEXT,
  address TEXT,
  profile_image TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  user_type TEXT CHECK (user_type IN ('customer', 'driver', 'admin'))
)
`;

export const createDriversTableSql = `
CREATE TABLE IF NOT EXISTS drivers (
  id UUID PRIMARY KEY REFERENCES profiles(id),
  national_id TEXT NOT NULL,
  license_number TEXT NOT NULL,
  license_image TEXT,
  vehicle_info JSONB NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  rejection_reason TEXT,
  rating DECIMAL(3,1),
  is_available BOOLEAN DEFAULT FALSE,
  location JSONB,
  documents JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
)
`;
