// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fszjrgfbgjpeuqjypwdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzempyZ2ZiZ2pwZXVxanlwd2RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTUzODcsImV4cCI6MjA2MDU3MTM4N30.mQtdM9hj-OnseK6YGmpG0oljWBd_L4wJJXLC0weyTSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);