// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdnqdigveyozsnoambph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkbnFkaWd2ZXlvenNub2FtYnBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MzE5ODMsImV4cCI6MjA2MDMwNzk4M30.LPSxgM8T3oWEp2FTJ0PPPGmVI04BAPDhIjUYXarjeTY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);